FROM openjdk:8-jre

MAINTAINER zhoujundi

WORKDIR /mall/server

ENV SERVER_PORT=8877

EXPOSE ${SERVER_PORT}

ADD ./target/platform-admin-api.jar ./app.jar

ENTRYPOINT ["java", \
            "-Djava.security.egd=file:/dev/./urandom", \
            "-Dserver.port=${SERVER_PORT}", \
            # 应用名称 如果想区分集群节点监控 改成不同的名称即可
#            "-Dskywalking.agent.service_name=ruoyi-server", \
#            "-javaagent:/ruoyi/skywalking/agent/skywalking-agent.jar", \
            "-jar", "app.jar"]
